apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: tinder-space
spec:
  ports:
    - port: 9092
      name: inside
    - port: 9093
      name: outside
  selector:
    app: kafka

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: tinder-space
spec:
  ports:
    - port: 2181
      name: client
      targetPort: 2181
  selector:
    app: zookeeper
