apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Shared infrastructure components
  sourceRepos:
    - 'https://github.com/Wildblazz/tinder-cloud.git'
  destinations:
    - namespace: infrastructure
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
