apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-serviceaccount
  namespace: ingress-kong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kong-ingress
rules:
  - apiGroups: [""]
    resources: [pods,services,endpoints,namespaces,secrets,configmaps,events]
    verbs: [get,list,watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create,patch,update]
  - apiGroups: ["discovery.k8s.io"]
    resources: [endpointslices]
    verbs: [get,list,watch]
  - apiGroups: ["networking.k8s.io"]
    resources: [ingresses,ingressclasses]
    verbs: [get,list,watch]
  - apiGroups: ["networking.k8s.io"]
    resources: [ingresses/status]
    verbs: [update,patch]
  - apiGroups: ["configuration.konghq.com"]
    resources:
      - kongplugins
      - kongclusterplugins
      - kongconsumers
      - kongingresses
      - tcpingresses
      - udpingresses
      - ingressclassparameterses
      - konglicenses
      - kongvaults
      - kongconsumergroups
      - kongcustomentities
      - kongupstreampolicies
    verbs: [get,list,watch,create,update,patch,delete]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: [gatewayclasses,gateways,httproutes,tcproutes,tlsroutes,udproutes,referencegrants]
    verbs: [get,list,watch]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: [customresourcedefinitions]
    verbs: [get,list,watch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kong-ingress-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kong-ingress
subjects:
  - kind: ServiceAccount
    name: kong-serviceaccount
    namespace: ingress-kong
