apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: ingress-kong
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
      nodePort: 30080
    - name: proxy-ssl
      port: 443
      targetPort: 8443
      nodePort: 30443
  selector:
    app: ingress-kong
