apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: ingress-kong
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 8444
      targetPort: 8001
  selector:
    app: ingress-kong
