apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: tinder-space
spec:
  type: ClusterIP
  selector:
    app: recommendation-service-app
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085
