apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
