apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: tinder-space
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30888
