apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: tinder-space
spec:
  type: ClusterIP
  selector:
    app: profile-service
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
