apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: infrastructure
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service.infrastructure.svc.cluster.local
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.infrastructure.svc.cluster.local:2181
            - name: KAFKA_BROKER_ID
              value: "1"
