apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: infrastructure
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://kafka-0.kafka.infrastructure.svc.cluster.local:9092,OUTSIDE://kafka-0.kafka.infrastructure.svc.cluster.local:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            - name: KAFKA_LISTENERS
              value: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.infrastructure.svc.cluster.local:2181
