apiVersion: v1
kind: Service
metadata:
  name: match-service
  namespace: tinder-space
spec:
  type: ClusterIP
  selector:
    app: match-service-app
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084
