apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reactions-ingress
  namespace: tinder-space
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  ingressClassName: kong
  rules:
    - host: $(DOMAIN_NAME)
      http:
        paths:
          - path: /api/reactions
            pathType: Prefix
            backend:
              service:
                name: reaction-service
                port:
                  number: 8083
